config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :listings
  resources :interests

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  get 'pages/about', to: 'pages#about'



  get 'users/:id' => 'users#show', as: :user
  # get 'signup', to: 'users#new'
  resources :users, except: [:new]
  #
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'

  get 'listings/type_select', to: 'listings#type_select'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :listing_categories
  has_many :categories, through: :listing_categories
  has_many :listing_interests
  has_many :interests, through: :listing_interests
  validates :title, presence: true, length: { minimum: 5, maximum: 35 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :user_id, presence: true

  validates :city, presence: true
  validates :interest_ids, presence: true
  validates :price, presence: true
  validates :price_time, presence: true
  validates :start_date, presence: true
  validates :tag_line, presence: true
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @listings = Listing.reorder("created_at DESC").page(params[:page]).per_page(5)
  end

  def new
    @listing = Listing.new

  end

  def edit
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      flash[:success] = "Listing was successfully created"
      redirect_to listing_path(@listing)
    else
      render 'new'
    end
  end

  def show

  end

  def destroy

    @listing.destroy
    flash[:danger] = "Listing was successfully deleted"
    redirect_to listings_path
  end

  def update

    if @listing.update(listing_params)
      flash[:success] = "Listing updated succcessfully"
      redirect_to listing_path(@listing)
    else
      render 'edit'
    end
  end

  private
    def listing_params
      params.require(:listing).permit(:title, :tag_line, :description, :listing_url, :companions, :price, :price_time,
                                     :start_date, :end_date, :city, category_ids: [], interest_ids: [])
    end

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def require_same_user
      if current_user != @listing.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own listing"
        redirect_to root_path
      end
    end

end

app/views/listings/_form.html.erb
<%= render 'shared/errors', obj: @listing %>
<div class="container-fluid">
  <div class="row">
<%= form_for(@listing, :html => {class: "form-horizontal", role: "form"}) do |f| %>




    <div class="col-xs-12 col-sm-12 col-md-3">
      <div class="title-category"><h4>What is the main interest of the trip?</br>
        <small>From your inerests <%= link_to 'Add more/change', edit_user_path(current_user) %> </small></h4></div>
          <%= f.collection_check_boxes :interest_ids, current_user.interests.all, :id, :name do |cb| %>
            <ul>
          <%= cb.label(class: "list-group-item list-group-item-on-bg checkbox-inline input_checkbox itme-list") {cb.check_box(class: "list-group-item checkbox ") + cb.text}  %>
        </ul>
      <% end %>
    </div>


    <div class="col-xs-12  col-md-6">
      <div class="form-container-listing">

        <div class="form-group">
          <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">

              <%= f.label :start_date %>
              <%= f.date_select :start_date, class: "form-control", placeholder: "Type, duration", autofocus: true %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">

                <%= f.label :end_date %>
                <%= f.date_select :end_date, class: "form-control", placeholder: "Type, duration", autofocus: true %>
              </div>
            </div>


        <div class="form-group">
          <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">

              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control", placeholder: "Type, duration", autofocus: true %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
                <%= f.label :tag_line %>
                <h4><small>Any words to recognize your trip</small></h4>
                <%= f.text_field :tag_line, class: "form-control", placeholder: "About the listing. Shortly.", autofocus: true %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
                  <%= f.label :city %>
                  <%= f.text_field :city, class: "form-control", placeholder: "Where are you going?", autofocus: true %>
                </div>
              </div>


          <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="form-group">
                    <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
                    <%= f.label :number_of_bedrooms_for_guests %>
                    <%= f.number_field :companions, class: "form-control", placeholder: "Type, duration", autofocus: true %>
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
                    <%= f.label :price %>
                    <%= f.select :price_time, options_for_select([['a Day','a Day'], ['in a Week', 'in a Week'], ['at Month', 'at Month']],  class: "dropdown-menu" )%>
                    <h4><small>Remeber to select price option</small></h4>
                    <div class="input-group">
                      <span class="input-group-addon">$</span>
                      <%= f.number_field :price, class: "form-control", placeholder: "Price", autofocus: true %>
                    </div>
                  </div>
                </div>
              </div>
            </div>



          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Url_to_the_listing %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.airbnb.com/</span>
                  <%= f.text_area :listing_url, rows: 1, class: "form-control", placeholder: "rooms/123456", autofocus: true %>
              </div>
            </div>
          </div>


          <div class="form-group">
                <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :description %>
              <%= f.text_area :description, rows: 7, class: "form-control", placeholder: "Desctiption of the listing", autofocus: true %>
            </div>
          </div>


  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
          <div class="btn-submit-listing">
          <%= f.submit class: 'btn btn-primary btn-lg btn-long'%>
        </div>
          </div>
        </div>
        </div>
      </div>


      <div class="col-xs-12 col-md-3">

        <div class="title-category"><h4>Please, select categories of the listing:</br>
          <small>One or many</small></h4></div>
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <ul>
            <%= cb.label(class: "list-group-item list-group-item-on-bg checkbox-inline input_checkbox itme-list") {cb.check_box(class: "list-group-item checkbox ") + cb.text}  %>
          </ul>
        <% end %>
      </div>

    </div>


  </div>
<% end %>

app/views/listings/_listing.html.erb
<% obj.each do |listing| %>
      <div class="well well-sm">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="listing-title">
              <%= link_to listing.title, listing_path(listing), class: "listing-title-text" %>
              <span class="badge badge-text badge-green"><strong>$<%= listing.price %></strong> <%= listing.price_time%></span>
              <h4><%= listing.tag_line %></h4>
              <p><%= render listing.interests %></p>
            </div>
          </div>
        </div>




            <div class="row">
              <div class="col-md-4">
                <ul class="list-group">
                  <li class="list-group-item"><span class="glyphicon glyphicon-user"></span><span class="badge"><%= listing.companions %> person/-s</span></li><hr class="zero-margin">
                  <% if listing.city %>
                  <li class="list-group-item"><span class="glyphicon glyphicon-globe"></span><span class="badge"><%= listing.city %></span></li><hr class="zero-margin">
                  <% else %>
                  <li class="list-group-item"><span class="glyphicon glyphicon-map-marker"></span><span class="badge">None</span></li><hr class="zero-margin">
                  <% end %>
                  <li class="list-group-item"><span class="glyphicon glyphicon-calendar"></span><span class="badge"><% if listing.start_date != nil %>
                  <%= listing.start_date.strftime("From %d-%b-%y") %>
                  <% end%></span></li><hr class="zero-margin">
                  <li class="list-group-item"><span class="glyphicon glyphicon-calendar"></span><span class="badge"><% if listing.end_date != nil %>
                  <%= listing.end_date.strftime("To %d-%b-%y") %>
                  <% end %></span></li><hr class="zero-margin">

                    <% if listing.listing_url != nil %>
                      <li class="list-group-item"><span class="glyphicon glyphicon-home"></span><span class="badge badge-green"><span class="glyphicon glyphicon-ok-circle"></span></span></li>
                    <% else  %>
                      <li class="list-group-item"><span class="glyphicon glyphicon-home"></span><span class="badge badge-red"><span class="glyphicon glyphicon-remove-circle"></span></span></li>
                    <% end %> </li>
                </ul>
              </div>
              <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <%= truncate(listing.description, length: 200) %></br>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <%= truncate(listing.description, length: 200) %></br>
                  </div>
                </div>
              </div>




          </div>

        <div class="container-fluid">
          <div class="row">
            <div class="panel panel-default">
              <div class="panel-body">
            <div class="col-md-12">
              <h4><small>Host of the trip:</small></h4>
                    <div class="listing-meta-details">

                    <small>  <%= image_tag listing.user.avatar.url(:thumb), class: "profilePhotoThumb" if listing.user.avatar? %>
                        <%= link_to listing.user.name, user_path(listing.user) %>  | Trip created
                                        <%= time_ago_in_words(listing.created_at) %> ago  |
                                        last updated: <%= time_ago_in_words(listing.updated_at) %> </small><hr>

                    </div>
                    <% if listing.categories.any? %>
                    <p>Categories: <%= render listing.categories %></p>
                    <% end %>
                    <% if user_signed_in? && (current_user == listing.user || current_user.admin?) %>
                      <div class="listing-actions">
                        <%= link_to 'Edit this listing', edit_listing_path(listing), class: "btn btn-xs btn-primary" %>
                        <%= link_to 'Delete this listing', listing_path(listing), method: :delete,
                                                            data: { confirm: "Are you sure you want to delete this listing?"},
                                                            class: "btn btn-xs btn-danger" %>
                      </div>
                    <% end %>
            </div>
          </div>

        </div>
      </div>
        </div>





    </div>
<% end %>

app/views/listings/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Planetome | Edit</title>

  </head>
<h1 align="center">Edit existing listing</h1>

<%= render 'form' %>

app/views/listings/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome | Listings</title>
  </head>
    <h1 align="center">List of all listings</h1>

    <!-- <ul class="nav nav-tabs nav-justified">
      <li role="presentation" class="active">
        <a href="#">Looking for Guest</a>
      </li>
      <li role="presentation">
        <a href="#">Looking for a Place</a>
      </li>
      <li role="presentation">
        <a href="#">Let's rent together</a>
      </li>
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Dropdown <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          ...
        </ul>
      </li>
    </ul> -->


      <div align="center">
        <%= will_paginate %>
      </div>
        <div class="container-fluid">
          <div class="row">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
              <%= render 'listing', obj: @listings %>
            </div>
          </div>
        </div>
      <div align="center">
        <%= will_paginate %>
      </div>





<!-- <p> Go to:  <%= link_to 'New Listing', new_listing_path %> | <%= link_to 'Main', root_path %> </p> -->

app/views/listings/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome | New Listing</title>
  </head>

  <h1 align="center">Create a listing</h1>

  <%= render 'form' %>

app/views/listings/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome | Show Listings</title>
  </head>
  <body id="show-listing-body">
  <div class="container-fluid">
    <div class="col-md-10 col-md-offset-1 ">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2 align="center"><strong><%= @listing.title %></strong></h2>
      </div>
    </div>
    </div>
<% if @listing.user %>
  <ul class="listing">
    <div class="container-fluid">
      <div class="row ">
        <div class="col-md-10 col-md-offset-1 ">
          <div class="container-fluid">
            <div class="row">
              <h3 class="center"><strong>Host:</strong></h3>
              <div class="panel panel-default">
                <div class="panel-body">
              <div class="col-sm-3 col-md-3 col-lg-3">
                <li><%= image_tag @listing.user.avatar.url(:medium), class: "profilePhoto" if @listing.user.avatar? %></li>
              </div>
              <div class="col-sm-9 col-md-9 col-lg-9">
                <li class="listing-title">
                  <%= link_to @listing.user.name, user_path(@listing.user), class: "listing-title-text" %>
                  <% if @listing.user.interests.any? %>
                <%= render @listing.user.interests %>
                <% end %>
                </li>
                <li><small>Planetome member for: <%= time_ago_in_words(@listing.user.created_at) %></small></li>
                  <li><small>Created <%= pluralize(@listing.user.listings.count, "listing") if @listing.user.listings %></small></li>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </ul>
  <% end %>
  <h3 class="center"><strong>Trip description:</strong></h3>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 ">
        <div class="panel panel-default">
          <div class="panel-body">
            <nav class="col-sm-6 col-md-4 col-lg-4 panel-data-position">
              <ul class="list-group">
                <li class="list-group-item">Price: <span class="badge badge-text">$<%= @listing.price %> <%= @listing.price_time%></span></li>
                <li class="list-group-item">Number of guests: <span class="badge"><%= @listing.companions %></span></li>
                <% if @listing.city %>
                <li class="list-group-item">City of destination: <span class="badge"><%= @listing.city %></span></li>
                <% end %>
                <li class="list-group-item">Country of destination:</li>
                <li class="list-group-item">Dates of the trip:</li>
                <li class="list-group-item"><% if @listing.interests.any? %>
                <p>Categories: <%= render @listing.interests %></p>
                <% end %></li>
                <li class="list-group-item"><% if @listing.categories.any? %>
                <p>Categories: <%= render @listing.categories %></p>
                <% end %></li>
              </ul>
            </nav>
            <div class="col-sm-6 col-md-7 col-lg-7">
              <%= simple_format(@listing.description) %>
            </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"
                <div class="btn-group" role="group" aria-label="...">
                  <%= link_to 'Send Request', new_user_registration_path, class: "btn btn-default btn-lg btn-long" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <h3 class="center"><strong>About the place:</strong></h3>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="listing-actions">
                <ul>
                <li class="list-group-item">  <% if @listing.listing_url != nil %>
                    <span class="label label-primary label-show-link"><%= link_to "Show living place", "https://airbnb.com/#{@listing.listing_url}", class: "badge-text",  :target => '_blank' %></span>
                  <% end %></span></li>
                  <li class="list-group-item">Report link</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>



      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="listing-actions">
                <small> Trip created <%= time_ago_in_words(@listing.created_at) %> ago  |
                        last updated: <%= time_ago_in_words(@listing.updated_at) %>
                </small>
              </div>
            </div>
          </div>
        </div>
      </div>




      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"
          <div align="center">
            <div class="btn-group center" role="group" aria-label="...">
              <%= link_to 'Request', new_user_registration_path, class: "btn btn-success btn-lg btn-request" %>
            </div>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="listing-actions">
                  <% if user_signed_in? && (current_user == @listing.user || current_user.admin?) %>
                      <%= link_to 'Edit this listing', edit_listing_path(@listing), class: "btn btn-xs btn-primary" %>
                      <%= link_to 'Delete this listing', listing_path(@listing), method: :delete,
                                                          data: { confirm: "Are you sure you want to delete this listing?"},
                                                          class: "btn btn-xs btn-danger" %>
                    <% end %>
                    <%= link_to 'View all listings', listings_path, class: "btn btn-xs btn-success" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/listings/type_select.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="radio radio-info">
  <input type="radio" name="survey" id="Radios1" value="Yes">
  <label>I'm looking for a place
  </label>
</div>
<div class="radio radio-info">
    <input type="radio" name="survey" id="Radios2" value="No">
  <label>I want to share my house
  </label>
</div>
</div>
<%= link_to 'New Listing', new_listing_path %>
</div>