config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :listings
  resources :interests

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  get 'pages/about', to: 'pages#about'



  get 'users/:id' => 'users#show', as: :user
  # get 'signup', to: 'users#new'
  resources :users, except: [:new]
  #
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'

  get 'listings/type_select', to: 'listings#type_select'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  has_many :user_interests
  has_many :users, through: :user_interests
  has_many :listing_interests
  has_many :listings, through: :listing_interests
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  def index
    @interests = Interest.all
  end

  def new
    @interest = Interest.new
  end

  def create
    @interest = Interest.new(interest_params)
    if @interest.save
      flash[:success] = "Interest was created succesfully"
      redirect_to interests_path
    else
      render 'new'
    end
  end

  def show
    @interest = Interest.find(params[:id])
  end



  private
  def interest_params
    params.require(:interest).permit(:name, :description)
  end

end

app/views/interests/_form.html.erb
<div class="container-fluid">
  <div class="row">
  <div class="col-md-12">
    <%= form_for(@interest, :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2  ">
          <%= f.label :description %>
        </div>
        <div class="col-sm-4 col-md-4 ">
          <%= f.text_area :description, rows: 3, class: "form-control", placeholder: "Desctiption of article", autofocus: true %>
        </div>
      </div>


      <div class="form-group">
        <div class="col-md-offset-4 col-md-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>


    <div class="col-md-5 col-md-offset-4">
      [ <%= link_to 'Cancel request and return to listings', listings_path %> ]
      </div>
    </div>
  </div>
</div>

app/views/interests/_interest.html.erb
<span class="badge badge-interest"><%= link_to interest.name, interest_path(interest), class: "badge-text-interest" %></span>

app/views/interests/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome Interests</title>
  </head>

<h1 align="center">Listing All Interests</h1>
<div class="container-fluid">
  <div class="row">
    <nav class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
      <ul class="list-group">
        <li class="list-group-item">
          <h1 align="center">Popular categories
          </h1>
        </li>
        <li class="list-group-item">
          <span class="badge">257</span>
          Photograpy
        </li>
        <li class="list-group-item">
          <span class="badge">324</span>
          Nightlife
        </li>
      </ul>
    </nav>
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-9 ">

          <ul class="listing">
            <div class="container-fluid">
              <div class="row">
                <% @interests.each do |interest| %>
                  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                    <div class="well">
                      <li class="article-title">
                          <h5>
                          <%= link_to "#{interest.name}", interest_path(interest) %>
                          </h5>
                          <h4><small>
                            <%= truncate(interest.description, length: 100) %>
                          </small></h4>
                      </li>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </ul>

    </div>
  </div>
</div>

app/views/interests/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome Create Interest</title>
  </head>
<h1 align="center">Create new interest</h1>


<%= render 'form' %>