config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :listings
  resources :interests

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  get 'pages/about', to: 'pages#about'



  get 'users/:id' => 'users#show', as: :user
  # get 'signup', to: 'users#new'
  resources :users, except: [:new]
  #
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'

  get 'listings/type_select', to: 'listings#type_select'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :listing_categories
  has_many :listings, through: :listing_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]


  def index
    @categories = Category.paginate(page: params[:page], per_page: 12)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created succesfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
    @category_listings = @category.listings.paginate(page: params[:page], per_page: 4)
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category was updated succcessfully"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end



  private
  def category_params
    params.require(:category).permit(:name, :description)
  end

  def require_admin
    if user_signed_in? and !current_user.admin?
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end


end

app/views/categories/_category.html.erb
<span class="badge badge-categories-blue"><%= link_to category.name, category_path(category), class: "badge-text" %></span>

app/views/categories/_form.html.erb
<div class="container-fluid">
  <div class="row">
  <div class="col-md-12">
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2  ">
          <%= f.label :description %>
        </div>
        <div class="col-sm-4 col-md-4 ">
          <%= f.text_area :description, rows: 3, class: "form-control", placeholder: "Desctiption of article", autofocus: true %>
        </div>
      </div>


      <div class="form-group">
        <div class="col-md-offset-4 col-md-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>


    <div class="col-md-5 col-md-offset-4">
      [ <%= link_to 'Cancel request and return to listings', listings_path %> ]
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome | Edit Category</title>
  </head>
<h1 align="center">Edit category</h1>


<%= render 'form' %>

app/views/categories/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome Categories</title>
  </head>

<h1 align="center">Listing All Categories</h1>
<div class="container-fluid">
  <div class="row">
    <nav class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
      <ul class="list-group">
        <li class="list-group-item">
          <h1 align="center">Popular categories
          </h1>
        </li>
        <!-- <li class="list-group-item">
        </li> -->
        <li class="list-group-item">
          <span class="badge">257</span>
          Photograpy
        </li>
        <li class="list-group-item">
          <span class="badge">324</span>
          Nightlife
        </li>
      </ul>
    </nav>
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-9 ">
      <div align="center">
        <%= will_paginate %></div>
          <ul class="listing">
            <div class="container-fluid">
              <div class="row">
                <% @categories.each do |category| %>
                  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                    <div class="well">
                      <li class="article-title">
                          <h5>
                          <%= link_to "#{category.name}", category_path(category) %>
                          </h5>
                        
                          <h4><small>
                            <%= truncate(category.description, length: 100) %>
                          </small></h4>
                      </li>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </ul>
        <div align="center">
      <%= will_paginate %></div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome Sign Up</title>
  </head>
<h1 align="center">Create new category</h1>


<%= render 'form' %>

app/views/categories/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Planetome | Show Listings</title>
  </head>
<h1 align="center"><%= "List of all listings in " + @category.name %></h1>
<h1 align="center"><small><%= @category.description %></small></h1>
<div align="center">
  <% if user_signed_in? and current_user.admin? %>
    <div class="row">
      <span class="badge edit-category-badge"><%= link_to "Edit Category Info", edit_category_path(@category), class: "edit-category" %></span>
    </div>
  <% end %>
  <%= will_paginate @category_listings %>
    </div>
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2">
            <%= render 'listings/listing', obj: @category_listings %>
          </div>
        </div>
      </div>
    <div align="center">
  <%= will_paginate @category_listings %>
</div>