config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :listings
  resources :interests

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  get 'pages/about', to: 'pages#about'



  get 'users/:id' => 'users#show', as: :user
  # get 'signup', to: 'users#new'
  resources :users, except: [:new]
  #
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'

  get 'listings/type_select', to: 'listings#type_select'

end

app/views/layouts/_footer.html.erb
<div class="footer-bottom">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
				<div class="copyright">
          <small>
            Copyright &copy; 2017 | <a href="http://www.planetome.com">Planetome Inc.</a>
            by Roman Mishiev.
          </small>
				</div>
			</div>
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <div class="footer-logo">
        <%= link_to image_tag('footer_logo.svg'), root_path %>
      </div>
      </div>
			<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
				<div class="design">
          <nav>
              <p><%= link_to 'About', pages_about_path %> |
              <%= link_to 'New Listing', new_listing_path %> |
              <%= link_to 'Show Listings', listings_path %></p>
          </nav>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_messages.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name} fade in" %>' role="alert">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('planetome_full.png',style: 'height:100%;width:auto;'), root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Listings", listings_path %><li>

        <li><li>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'New Listing', new_listing_path %></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'All Interests', categories_path %></li>
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %></li>
                <% end %>
                <% if user_signed_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create new Category", new_category_path %></li>
                <% end %>

              </ul>
            </li>
      </ul>
      <!-- <form class="navbar-form navbar-left hidden-md hidden-sm">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-success">Go!</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
            <!-- <li id="nav-guest" ><a href="#">Find a Trip</a></li> -->
            <% if user_signed_in? %>
            <li id="nav-host"><span class="label label-info label-host"><%= link_to 'Host a Place', new_listing_path %></span></li>
            <% end %>


            <% if user_signed_in? %>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your <%= "admin" if current_user.admin? %> profile<span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <% if current_user  %>
                <div class="row">
                  <div class="col-md-5">
                    <li class="navimage">

                      <% if current_user.avatar?  %>
                      <%= image_tag current_user.avatar.url(:thumb), class: "profilePhotoThumb" %>
                      <% else %>
                      <%= gravatar_for current_user, size: 20 %></li>
                      <% end %>



                  </div>
                  <div class="col-md-7 ">
                    <li class="navname"><%= current_user.name %></li>
                  </div>
                </div>

                <% end %>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'View your public profile', user_path(current_user)%></li>
                <li><a href="#">View your profile data</a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Edit your profile', edit_user_path(current_user)%></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Edit password & email', edit_user_registration_path(current_user)%></li>
              </ul>
            </li>
            <% else %>

          <li><%= link_to  new_user_session_path do %>
            <p id="p-margin-b-0" ><span class="glyphicon glyphicon-log-in"></span> Log In</p><% end %></li>
          <li><%= link_to  new_user_registration_path do %>
            <p id="p-margin-b-0" ><span class="glyphicon glyphicon-pencil"></span> Sign Up</p><% end %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet" type="text/css" />
    <!-- <link rel="stylesheet" href="awesomplete.css" />
    <script src="awesomplete.js" async></script> -->
  </head>

  <body id="show-listing-body">
    <%= render 'layouts/navigation' %>

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
      <!-- <%= debug(params) if Rails.env.development? %> -->

  </body>

    <%= render 'layouts/footer' %>

</html>